// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: healthcheck.proto
#ifndef GRPC_healthcheck_2eproto__INCLUDED
#define GRPC_healthcheck_2eproto__INCLUDED

#include "healthcheck.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace healthcheck {

class HealthCheck final {
 public:
  static constexpr char const* service_full_name() {
    return "healthcheck.HealthCheck";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::healthcheck::HealthCheckResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::healthcheck::HealthCheckResponse>> AsyncDo(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::healthcheck::HealthCheckResponse>>(AsyncDoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::healthcheck::HealthCheckResponse>> PrepareAsyncDo(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::healthcheck::HealthCheckResponse>>(PrepareAsyncDoRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::healthcheck::HealthCheckResponse>* AsyncDoRaw(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::healthcheck::HealthCheckResponse>* PrepareAsyncDoRaw(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::healthcheck::HealthCheckResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>> AsyncDo(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>>(AsyncDoRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>> PrepareAsyncDo(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>>(PrepareAsyncDoRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, std::function<void(::grpc::Status)>) override;
      void Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>* AsyncDoRaw(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>* PrepareAsyncDoRaw(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Do_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Do(::grpc::ServerContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Do : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Do() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Do() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Do(::grpc::ServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDo(::grpc::ServerContext* context, ::healthcheck::HealthCheckRequest* request, ::grpc::ServerAsyncResponseWriter< ::healthcheck::HealthCheckResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Do<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Do : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_Do() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::healthcheck::HealthCheckRequest, ::healthcheck::HealthCheckResponse>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response) { return this->Do(context, request, response); }));}
    void SetMessageAllocatorFor_Do(
        ::grpc::experimental::MessageAllocator< ::healthcheck::HealthCheckRequest, ::healthcheck::HealthCheckResponse>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::healthcheck::HealthCheckRequest, ::healthcheck::HealthCheckResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_Do() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Do(::grpc::ServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Do(
      ::grpc::CallbackServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Do(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_Do<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_Do<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Do : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Do() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Do() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Do(::grpc::ServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Do : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Do() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Do() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Do(::grpc::ServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestDo(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Do : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_Do() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Do(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_Do() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Do(::grpc::ServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* Do(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* Do(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Do : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Do() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::healthcheck::HealthCheckRequest, ::healthcheck::HealthCheckResponse>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::healthcheck::HealthCheckRequest, ::healthcheck::HealthCheckResponse>* streamer) {
                       return this->StreamedDo(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Do() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Do(::grpc::ServerContext* /*context*/, const ::healthcheck::HealthCheckRequest* /*request*/, ::healthcheck::HealthCheckResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedDo(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::healthcheck::HealthCheckRequest,::healthcheck::HealthCheckResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Do<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Do<Service > StreamedService;
};

}  // namespace healthcheck


#endif  // GRPC_healthcheck_2eproto__INCLUDED
