// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: healthcheck.proto

#include "healthcheck.pb.h"
#include "healthcheck.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace healthcheck {

static const char* HealthCheck_method_names[] = {
  "/healthcheck.HealthCheck/Do",
};

std::unique_ptr< HealthCheck::Stub> HealthCheck::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< HealthCheck::Stub> stub(new HealthCheck::Stub(channel));
  return stub;
}

HealthCheck::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Do_(HealthCheck_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status HealthCheck::Stub::Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::healthcheck::HealthCheckResponse* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Do_, context, request, response);
}

void HealthCheck::Stub::experimental_async::Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Do_, context, request, response, std::move(f));
}

void HealthCheck::Stub::experimental_async::Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Do_, context, request, response, std::move(f));
}

void HealthCheck::Stub::experimental_async::Do(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Do_, context, request, response, reactor);
}

void HealthCheck::Stub::experimental_async::Do(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::healthcheck::HealthCheckResponse* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Do_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>* HealthCheck::Stub::AsyncDoRaw(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::healthcheck::HealthCheckResponse>::Create(channel_.get(), cq, rpcmethod_Do_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::healthcheck::HealthCheckResponse>* HealthCheck::Stub::PrepareAsyncDoRaw(::grpc::ClientContext* context, const ::healthcheck::HealthCheckRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::healthcheck::HealthCheckResponse>::Create(channel_.get(), cq, rpcmethod_Do_, context, request, false);
}

HealthCheck::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      HealthCheck_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< HealthCheck::Service, ::healthcheck::HealthCheckRequest, ::healthcheck::HealthCheckResponse>(
          [](HealthCheck::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::healthcheck::HealthCheckRequest* req,
             ::healthcheck::HealthCheckResponse* resp) {
               return service->Do(ctx, req, resp);
             }, this)));
}

HealthCheck::Service::~Service() {
}

::grpc::Status HealthCheck::Service::Do(::grpc::ServerContext* context, const ::healthcheck::HealthCheckRequest* request, ::healthcheck::HealthCheckResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace healthcheck

