// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hotmethod.proto

#include "hotmethod.pb.h"
#include "hotmethod.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace hotmethod {

static const char* Hotmethod_method_names[] = {
  "/hotmethod.Hotmethod/NotifyResult",
};

std::unique_ptr< Hotmethod::Stub> Hotmethod::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Hotmethod::Stub> stub(new Hotmethod::Stub(channel));
  return stub;
}

Hotmethod::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_NotifyResult_(Hotmethod_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Hotmethod::Stub::NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::hotmethod::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_NotifyResult_, context, request, response);
}

void Hotmethod::Stub::experimental_async::NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_NotifyResult_, context, request, response, std::move(f));
}

void Hotmethod::Stub::experimental_async::NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_NotifyResult_, context, request, response, std::move(f));
}

void Hotmethod::Stub::experimental_async::NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_NotifyResult_, context, request, response, reactor);
}

void Hotmethod::Stub::experimental_async::NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_NotifyResult_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>* Hotmethod::Stub::AsyncNotifyResultRaw(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::hotmethod::Empty>::Create(channel_.get(), cq, rpcmethod_NotifyResult_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>* Hotmethod::Stub::PrepareAsyncNotifyResultRaw(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::hotmethod::Empty>::Create(channel_.get(), cq, rpcmethod_NotifyResult_, context, request, false);
}

Hotmethod::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Hotmethod_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Hotmethod::Service, ::hotmethod::TaskResult, ::hotmethod::Empty>(
          [](Hotmethod::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::hotmethod::TaskResult* req,
             ::hotmethod::Empty* resp) {
               return service->NotifyResult(ctx, req, resp);
             }, this)));
}

Hotmethod::Service::~Service() {
}

::grpc::Status Hotmethod::Service::NotifyResult(::grpc::ServerContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace hotmethod

