// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotmethod.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_hotmethod_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_hotmethod_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "common.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_hotmethod_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_hotmethod_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_hotmethod_2eproto;
namespace hotmethod {
class Empty;
class EmptyDefaultTypeInternal;
extern EmptyDefaultTypeInternal _Empty_default_instance_;
class RecordArgv;
class RecordArgvDefaultTypeInternal;
extern RecordArgvDefaultTypeInternal _RecordArgv_default_instance_;
class TaskDesc;
class TaskDescDefaultTypeInternal;
extern TaskDescDefaultTypeInternal _TaskDesc_default_instance_;
class TaskResult;
class TaskResultDefaultTypeInternal;
extern TaskResultDefaultTypeInternal _TaskResult_default_instance_;
}  // namespace hotmethod
PROTOBUF_NAMESPACE_OPEN
template<> ::hotmethod::Empty* Arena::CreateMaybeMessage<::hotmethod::Empty>(Arena*);
template<> ::hotmethod::RecordArgv* Arena::CreateMaybeMessage<::hotmethod::RecordArgv>(Arena*);
template<> ::hotmethod::TaskDesc* Arena::CreateMaybeMessage<::hotmethod::TaskDesc>(Arena*);
template<> ::hotmethod::TaskResult* Arena::CreateMaybeMessage<::hotmethod::TaskResult>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace hotmethod {

// ===================================================================

class TaskDesc PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hotmethod.TaskDesc) */ {
 public:
  inline TaskDesc() : TaskDesc(nullptr) {};
  virtual ~TaskDesc();

  TaskDesc(const TaskDesc& from);
  TaskDesc(TaskDesc&& from) noexcept
    : TaskDesc() {
    *this = ::std::move(from);
  }

  inline TaskDesc& operator=(const TaskDesc& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskDesc& operator=(TaskDesc&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TaskDesc& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TaskDesc* internal_default_instance() {
    return reinterpret_cast<const TaskDesc*>(
               &_TaskDesc_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(TaskDesc& a, TaskDesc& b) {
    a.Swap(&b);
  }
  inline void Swap(TaskDesc* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskDesc* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TaskDesc* New() const final {
    return CreateMaybeMessage<TaskDesc>(nullptr);
  }

  TaskDesc* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TaskDesc>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TaskDesc& from);
  void MergeFrom(const TaskDesc& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaskDesc* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hotmethod.TaskDesc";
  }
  protected:
  explicit TaskDesc(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hotmethod_2eproto);
    return ::descriptor_table_hotmethod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTaskIdFieldNumber = 1,
    kContainerNameFieldNumber = 5,
    kSampleArgvFieldNumber = 4,
    kCosConfigFieldNumber = 8,
    kTaskTypeFieldNumber = 2,
    kProfilerTypeFieldNumber = 3,
    kTimeoutSecFieldNumber = 7,
  };
  // string task_id = 1;
  void clear_task_id();
  const std::string& task_id() const;
  void set_task_id(const std::string& value);
  void set_task_id(std::string&& value);
  void set_task_id(const char* value);
  void set_task_id(const char* value, size_t size);
  std::string* mutable_task_id();
  std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_task_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_task_id(
      std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // string container_name = 5;
  void clear_container_name();
  const std::string& container_name() const;
  void set_container_name(const std::string& value);
  void set_container_name(std::string&& value);
  void set_container_name(const char* value);
  void set_container_name(const char* value, size_t size);
  std::string* mutable_container_name();
  std::string* release_container_name();
  void set_allocated_container_name(std::string* container_name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_container_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_container_name(
      std::string* container_name);
  private:
  const std::string& _internal_container_name() const;
  void _internal_set_container_name(const std::string& value);
  std::string* _internal_mutable_container_name();
  public:

  // .hotmethod.RecordArgv sample_argv = 4;
  bool has_sample_argv() const;
  private:
  bool _internal_has_sample_argv() const;
  public:
  void clear_sample_argv();
  const ::hotmethod::RecordArgv& sample_argv() const;
  ::hotmethod::RecordArgv* release_sample_argv();
  ::hotmethod::RecordArgv* mutable_sample_argv();
  void set_allocated_sample_argv(::hotmethod::RecordArgv* sample_argv);
  private:
  const ::hotmethod::RecordArgv& _internal_sample_argv() const;
  ::hotmethod::RecordArgv* _internal_mutable_sample_argv();
  public:
  void unsafe_arena_set_allocated_sample_argv(
      ::hotmethod::RecordArgv* sample_argv);
  ::hotmethod::RecordArgv* unsafe_arena_release_sample_argv();

  // .common.CosConfig cos_config = 8;
  bool has_cos_config() const;
  private:
  bool _internal_has_cos_config() const;
  public:
  void clear_cos_config();
  const ::common::CosConfig& cos_config() const;
  ::common::CosConfig* release_cos_config();
  ::common::CosConfig* mutable_cos_config();
  void set_allocated_cos_config(::common::CosConfig* cos_config);
  private:
  const ::common::CosConfig& _internal_cos_config() const;
  ::common::CosConfig* _internal_mutable_cos_config();
  public:
  void unsafe_arena_set_allocated_cos_config(
      ::common::CosConfig* cos_config);
  ::common::CosConfig* unsafe_arena_release_cos_config();

  // uint32 task_type = 2;
  void clear_task_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 task_type() const;
  void set_task_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_task_type() const;
  void _internal_set_task_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 profiler_type = 3;
  void clear_profiler_type();
  ::PROTOBUF_NAMESPACE_ID::uint32 profiler_type() const;
  void set_profiler_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_profiler_type() const;
  void _internal_set_profiler_type(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // uint32 timeout_sec = 7;
  void clear_timeout_sec();
  ::PROTOBUF_NAMESPACE_ID::uint32 timeout_sec() const;
  void set_timeout_sec(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_timeout_sec() const;
  void _internal_set_timeout_sec(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:hotmethod.TaskDesc)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr container_name_;
  ::hotmethod::RecordArgv* sample_argv_;
  ::common::CosConfig* cos_config_;
  ::PROTOBUF_NAMESPACE_ID::uint32 task_type_;
  ::PROTOBUF_NAMESPACE_ID::uint32 profiler_type_;
  ::PROTOBUF_NAMESPACE_ID::uint32 timeout_sec_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hotmethod_2eproto;
};
// -------------------------------------------------------------------

class RecordArgv PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hotmethod.RecordArgv) */ {
 public:
  inline RecordArgv() : RecordArgv(nullptr) {};
  virtual ~RecordArgv();

  RecordArgv(const RecordArgv& from);
  RecordArgv(RecordArgv&& from) noexcept
    : RecordArgv() {
    *this = ::std::move(from);
  }

  inline RecordArgv& operator=(const RecordArgv& from) {
    CopyFrom(from);
    return *this;
  }
  inline RecordArgv& operator=(RecordArgv&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const RecordArgv& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const RecordArgv* internal_default_instance() {
    return reinterpret_cast<const RecordArgv*>(
               &_RecordArgv_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(RecordArgv& a, RecordArgv& b) {
    a.Swap(&b);
  }
  inline void Swap(RecordArgv* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(RecordArgv* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline RecordArgv* New() const final {
    return CreateMaybeMessage<RecordArgv>(nullptr);
  }

  RecordArgv* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<RecordArgv>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const RecordArgv& from);
  void MergeFrom(const RecordArgv& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(RecordArgv* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hotmethod.RecordArgv";
  }
  protected:
  explicit RecordArgv(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hotmethod_2eproto);
    return ::descriptor_table_hotmethod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCallgraphFieldNumber = 4,
    kDurationFieldNumber = 2,
    kHzFieldNumber = 1,
    kPidFieldNumber = 3,
  };
  // string callgraph = 4;
  void clear_callgraph();
  const std::string& callgraph() const;
  void set_callgraph(const std::string& value);
  void set_callgraph(std::string&& value);
  void set_callgraph(const char* value);
  void set_callgraph(const char* value, size_t size);
  std::string* mutable_callgraph();
  std::string* release_callgraph();
  void set_allocated_callgraph(std::string* callgraph);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_callgraph();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_callgraph(
      std::string* callgraph);
  private:
  const std::string& _internal_callgraph() const;
  void _internal_set_callgraph(const std::string& value);
  std::string* _internal_mutable_callgraph();
  public:

  // uint64 duration = 2;
  void clear_duration();
  ::PROTOBUF_NAMESPACE_ID::uint64 duration() const;
  void set_duration(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_duration() const;
  void _internal_set_duration(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint32 hz = 1;
  void clear_hz();
  ::PROTOBUF_NAMESPACE_ID::uint32 hz() const;
  void set_hz(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_hz() const;
  void _internal_set_hz(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // int32 pid = 3;
  void clear_pid();
  ::PROTOBUF_NAMESPACE_ID::int32 pid() const;
  void set_pid(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_pid() const;
  void _internal_set_pid(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:hotmethod.RecordArgv)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr callgraph_;
  ::PROTOBUF_NAMESPACE_ID::uint64 duration_;
  ::PROTOBUF_NAMESPACE_ID::uint32 hz_;
  ::PROTOBUF_NAMESPACE_ID::int32 pid_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hotmethod_2eproto;
};
// -------------------------------------------------------------------

class TaskResult PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hotmethod.TaskResult) */ {
 public:
  inline TaskResult() : TaskResult(nullptr) {};
  virtual ~TaskResult();

  TaskResult(const TaskResult& from);
  TaskResult(TaskResult&& from) noexcept
    : TaskResult() {
    *this = ::std::move(from);
  }

  inline TaskResult& operator=(const TaskResult& from) {
    CopyFrom(from);
    return *this;
  }
  inline TaskResult& operator=(TaskResult&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const TaskResult& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const TaskResult* internal_default_instance() {
    return reinterpret_cast<const TaskResult*>(
               &_TaskResult_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(TaskResult& a, TaskResult& b) {
    a.Swap(&b);
  }
  inline void Swap(TaskResult* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TaskResult* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline TaskResult* New() const final {
    return CreateMaybeMessage<TaskResult>(nullptr);
  }

  TaskResult* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<TaskResult>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const TaskResult& from);
  void MergeFrom(const TaskResult& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TaskResult* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hotmethod.TaskResult";
  }
  protected:
  explicit TaskResult(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hotmethod_2eproto);
    return ::descriptor_table_hotmethod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kTaskIdFieldNumber = 1,
    kErrorMessageFieldNumber = 2,
    kCosKeyFieldNumber = 4,
  };
  // string task_id = 1;
  void clear_task_id();
  const std::string& task_id() const;
  void set_task_id(const std::string& value);
  void set_task_id(std::string&& value);
  void set_task_id(const char* value);
  void set_task_id(const char* value, size_t size);
  std::string* mutable_task_id();
  std::string* release_task_id();
  void set_allocated_task_id(std::string* task_id);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_task_id();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_task_id(
      std::string* task_id);
  private:
  const std::string& _internal_task_id() const;
  void _internal_set_task_id(const std::string& value);
  std::string* _internal_mutable_task_id();
  public:

  // string error_message = 2;
  void clear_error_message();
  const std::string& error_message() const;
  void set_error_message(const std::string& value);
  void set_error_message(std::string&& value);
  void set_error_message(const char* value);
  void set_error_message(const char* value, size_t size);
  std::string* mutable_error_message();
  std::string* release_error_message();
  void set_allocated_error_message(std::string* error_message);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_error_message();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_error_message(
      std::string* error_message);
  private:
  const std::string& _internal_error_message() const;
  void _internal_set_error_message(const std::string& value);
  std::string* _internal_mutable_error_message();
  public:

  // string cos_key = 4;
  void clear_cos_key();
  const std::string& cos_key() const;
  void set_cos_key(const std::string& value);
  void set_cos_key(std::string&& value);
  void set_cos_key(const char* value);
  void set_cos_key(const char* value, size_t size);
  std::string* mutable_cos_key();
  std::string* release_cos_key();
  void set_allocated_cos_key(std::string* cos_key);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_cos_key();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_cos_key(
      std::string* cos_key);
  private:
  const std::string& _internal_cos_key() const;
  void _internal_set_cos_key(const std::string& value);
  std::string* _internal_mutable_cos_key();
  public:

  // @@protoc_insertion_point(class_scope:hotmethod.TaskResult)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr task_id_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr error_message_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr cos_key_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hotmethod_2eproto;
};
// -------------------------------------------------------------------

class Empty PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:hotmethod.Empty) */ {
 public:
  inline Empty() : Empty(nullptr) {};
  virtual ~Empty();

  Empty(const Empty& from);
  Empty(Empty&& from) noexcept
    : Empty() {
    *this = ::std::move(from);
  }

  inline Empty& operator=(const Empty& from) {
    CopyFrom(from);
    return *this;
  }
  inline Empty& operator=(Empty&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Empty& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Empty* internal_default_instance() {
    return reinterpret_cast<const Empty*>(
               &_Empty_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Empty& a, Empty& b) {
    a.Swap(&b);
  }
  inline void Swap(Empty* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Empty* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Empty* New() const final {
    return CreateMaybeMessage<Empty>(nullptr);
  }

  Empty* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Empty>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Empty& from);
  void MergeFrom(const Empty& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Empty* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "hotmethod.Empty";
  }
  protected:
  explicit Empty(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_hotmethod_2eproto);
    return ::descriptor_table_hotmethod_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:hotmethod.Empty)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_hotmethod_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// TaskDesc

// string task_id = 1;
inline void TaskDesc::clear_task_id() {
  task_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TaskDesc::task_id() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskDesc.task_id)
  return _internal_task_id();
}
inline void TaskDesc::set_task_id(const std::string& value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskDesc.task_id)
}
inline std::string* TaskDesc::mutable_task_id() {
  // @@protoc_insertion_point(field_mutable:hotmethod.TaskDesc.task_id)
  return _internal_mutable_task_id();
}
inline const std::string& TaskDesc::_internal_task_id() const {
  return task_id_.Get();
}
inline void TaskDesc::_internal_set_task_id(const std::string& value) {
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TaskDesc::set_task_id(std::string&& value) {
  
  task_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hotmethod.TaskDesc.task_id)
}
inline void TaskDesc::set_task_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hotmethod.TaskDesc.task_id)
}
inline void TaskDesc::set_task_id(const char* value,
    size_t size) {
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hotmethod.TaskDesc.task_id)
}
inline std::string* TaskDesc::_internal_mutable_task_id() {
  
  return task_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TaskDesc::release_task_id() {
  // @@protoc_insertion_point(field_release:hotmethod.TaskDesc.task_id)
  return task_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TaskDesc::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  task_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hotmethod.TaskDesc.task_id)
}
inline std::string* TaskDesc::unsafe_arena_release_task_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hotmethod.TaskDesc.task_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return task_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TaskDesc::unsafe_arena_set_allocated_task_id(
    std::string* task_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (task_id != nullptr) {
    
  } else {
    
  }
  task_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      task_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.TaskDesc.task_id)
}

// uint32 task_type = 2;
inline void TaskDesc::clear_task_type() {
  task_type_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TaskDesc::_internal_task_type() const {
  return task_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TaskDesc::task_type() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskDesc.task_type)
  return _internal_task_type();
}
inline void TaskDesc::_internal_set_task_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  task_type_ = value;
}
inline void TaskDesc::set_task_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_task_type(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskDesc.task_type)
}

// uint32 profiler_type = 3;
inline void TaskDesc::clear_profiler_type() {
  profiler_type_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TaskDesc::_internal_profiler_type() const {
  return profiler_type_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TaskDesc::profiler_type() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskDesc.profiler_type)
  return _internal_profiler_type();
}
inline void TaskDesc::_internal_set_profiler_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  profiler_type_ = value;
}
inline void TaskDesc::set_profiler_type(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_profiler_type(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskDesc.profiler_type)
}

// .hotmethod.RecordArgv sample_argv = 4;
inline bool TaskDesc::_internal_has_sample_argv() const {
  return this != internal_default_instance() && sample_argv_ != nullptr;
}
inline bool TaskDesc::has_sample_argv() const {
  return _internal_has_sample_argv();
}
inline void TaskDesc::clear_sample_argv() {
  if (GetArena() == nullptr && sample_argv_ != nullptr) {
    delete sample_argv_;
  }
  sample_argv_ = nullptr;
}
inline const ::hotmethod::RecordArgv& TaskDesc::_internal_sample_argv() const {
  const ::hotmethod::RecordArgv* p = sample_argv_;
  return p != nullptr ? *p : *reinterpret_cast<const ::hotmethod::RecordArgv*>(
      &::hotmethod::_RecordArgv_default_instance_);
}
inline const ::hotmethod::RecordArgv& TaskDesc::sample_argv() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskDesc.sample_argv)
  return _internal_sample_argv();
}
inline void TaskDesc::unsafe_arena_set_allocated_sample_argv(
    ::hotmethod::RecordArgv* sample_argv) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(sample_argv_);
  }
  sample_argv_ = sample_argv;
  if (sample_argv) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.TaskDesc.sample_argv)
}
inline ::hotmethod::RecordArgv* TaskDesc::release_sample_argv() {
  auto temp = unsafe_arena_release_sample_argv();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::hotmethod::RecordArgv* TaskDesc::unsafe_arena_release_sample_argv() {
  // @@protoc_insertion_point(field_release:hotmethod.TaskDesc.sample_argv)
  
  ::hotmethod::RecordArgv* temp = sample_argv_;
  sample_argv_ = nullptr;
  return temp;
}
inline ::hotmethod::RecordArgv* TaskDesc::_internal_mutable_sample_argv() {
  
  if (sample_argv_ == nullptr) {
    auto* p = CreateMaybeMessage<::hotmethod::RecordArgv>(GetArena());
    sample_argv_ = p;
  }
  return sample_argv_;
}
inline ::hotmethod::RecordArgv* TaskDesc::mutable_sample_argv() {
  // @@protoc_insertion_point(field_mutable:hotmethod.TaskDesc.sample_argv)
  return _internal_mutable_sample_argv();
}
inline void TaskDesc::set_allocated_sample_argv(::hotmethod::RecordArgv* sample_argv) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete sample_argv_;
  }
  if (sample_argv) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(sample_argv);
    if (message_arena != submessage_arena) {
      sample_argv = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, sample_argv, submessage_arena);
    }
    
  } else {
    
  }
  sample_argv_ = sample_argv;
  // @@protoc_insertion_point(field_set_allocated:hotmethod.TaskDesc.sample_argv)
}

// string container_name = 5;
inline void TaskDesc::clear_container_name() {
  container_name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TaskDesc::container_name() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskDesc.container_name)
  return _internal_container_name();
}
inline void TaskDesc::set_container_name(const std::string& value) {
  _internal_set_container_name(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskDesc.container_name)
}
inline std::string* TaskDesc::mutable_container_name() {
  // @@protoc_insertion_point(field_mutable:hotmethod.TaskDesc.container_name)
  return _internal_mutable_container_name();
}
inline const std::string& TaskDesc::_internal_container_name() const {
  return container_name_.Get();
}
inline void TaskDesc::_internal_set_container_name(const std::string& value) {
  
  container_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TaskDesc::set_container_name(std::string&& value) {
  
  container_name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hotmethod.TaskDesc.container_name)
}
inline void TaskDesc::set_container_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  container_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hotmethod.TaskDesc.container_name)
}
inline void TaskDesc::set_container_name(const char* value,
    size_t size) {
  
  container_name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hotmethod.TaskDesc.container_name)
}
inline std::string* TaskDesc::_internal_mutable_container_name() {
  
  return container_name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TaskDesc::release_container_name() {
  // @@protoc_insertion_point(field_release:hotmethod.TaskDesc.container_name)
  return container_name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TaskDesc::set_allocated_container_name(std::string* container_name) {
  if (container_name != nullptr) {
    
  } else {
    
  }
  container_name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), container_name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hotmethod.TaskDesc.container_name)
}
inline std::string* TaskDesc::unsafe_arena_release_container_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hotmethod.TaskDesc.container_name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return container_name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TaskDesc::unsafe_arena_set_allocated_container_name(
    std::string* container_name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (container_name != nullptr) {
    
  } else {
    
  }
  container_name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      container_name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.TaskDesc.container_name)
}

// uint32 timeout_sec = 7;
inline void TaskDesc::clear_timeout_sec() {
  timeout_sec_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TaskDesc::_internal_timeout_sec() const {
  return timeout_sec_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 TaskDesc::timeout_sec() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskDesc.timeout_sec)
  return _internal_timeout_sec();
}
inline void TaskDesc::_internal_set_timeout_sec(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  timeout_sec_ = value;
}
inline void TaskDesc::set_timeout_sec(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_timeout_sec(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskDesc.timeout_sec)
}

// .common.CosConfig cos_config = 8;
inline bool TaskDesc::_internal_has_cos_config() const {
  return this != internal_default_instance() && cos_config_ != nullptr;
}
inline bool TaskDesc::has_cos_config() const {
  return _internal_has_cos_config();
}
inline const ::common::CosConfig& TaskDesc::_internal_cos_config() const {
  const ::common::CosConfig* p = cos_config_;
  return p != nullptr ? *p : *reinterpret_cast<const ::common::CosConfig*>(
      &::common::_CosConfig_default_instance_);
}
inline const ::common::CosConfig& TaskDesc::cos_config() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskDesc.cos_config)
  return _internal_cos_config();
}
inline void TaskDesc::unsafe_arena_set_allocated_cos_config(
    ::common::CosConfig* cos_config) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(cos_config_);
  }
  cos_config_ = cos_config;
  if (cos_config) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.TaskDesc.cos_config)
}
inline ::common::CosConfig* TaskDesc::release_cos_config() {
  auto temp = unsafe_arena_release_cos_config();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::common::CosConfig* TaskDesc::unsafe_arena_release_cos_config() {
  // @@protoc_insertion_point(field_release:hotmethod.TaskDesc.cos_config)
  
  ::common::CosConfig* temp = cos_config_;
  cos_config_ = nullptr;
  return temp;
}
inline ::common::CosConfig* TaskDesc::_internal_mutable_cos_config() {
  
  if (cos_config_ == nullptr) {
    auto* p = CreateMaybeMessage<::common::CosConfig>(GetArena());
    cos_config_ = p;
  }
  return cos_config_;
}
inline ::common::CosConfig* TaskDesc::mutable_cos_config() {
  // @@protoc_insertion_point(field_mutable:hotmethod.TaskDesc.cos_config)
  return _internal_mutable_cos_config();
}
inline void TaskDesc::set_allocated_cos_config(::common::CosConfig* cos_config) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete reinterpret_cast< ::PROTOBUF_NAMESPACE_ID::MessageLite*>(cos_config_);
  }
  if (cos_config) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(cos_config)->GetArena();
    if (message_arena != submessage_arena) {
      cos_config = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, cos_config, submessage_arena);
    }
    
  } else {
    
  }
  cos_config_ = cos_config;
  // @@protoc_insertion_point(field_set_allocated:hotmethod.TaskDesc.cos_config)
}

// -------------------------------------------------------------------

// RecordArgv

// uint32 hz = 1;
inline void RecordArgv::clear_hz() {
  hz_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 RecordArgv::_internal_hz() const {
  return hz_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 RecordArgv::hz() const {
  // @@protoc_insertion_point(field_get:hotmethod.RecordArgv.hz)
  return _internal_hz();
}
inline void RecordArgv::_internal_set_hz(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  hz_ = value;
}
inline void RecordArgv::set_hz(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_hz(value);
  // @@protoc_insertion_point(field_set:hotmethod.RecordArgv.hz)
}

// uint64 duration = 2;
inline void RecordArgv::clear_duration() {
  duration_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RecordArgv::_internal_duration() const {
  return duration_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 RecordArgv::duration() const {
  // @@protoc_insertion_point(field_get:hotmethod.RecordArgv.duration)
  return _internal_duration();
}
inline void RecordArgv::_internal_set_duration(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  duration_ = value;
}
inline void RecordArgv::set_duration(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_duration(value);
  // @@protoc_insertion_point(field_set:hotmethod.RecordArgv.duration)
}

// int32 pid = 3;
inline void RecordArgv::clear_pid() {
  pid_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RecordArgv::_internal_pid() const {
  return pid_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 RecordArgv::pid() const {
  // @@protoc_insertion_point(field_get:hotmethod.RecordArgv.pid)
  return _internal_pid();
}
inline void RecordArgv::_internal_set_pid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  pid_ = value;
}
inline void RecordArgv::set_pid(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:hotmethod.RecordArgv.pid)
}

// string callgraph = 4;
inline void RecordArgv::clear_callgraph() {
  callgraph_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& RecordArgv::callgraph() const {
  // @@protoc_insertion_point(field_get:hotmethod.RecordArgv.callgraph)
  return _internal_callgraph();
}
inline void RecordArgv::set_callgraph(const std::string& value) {
  _internal_set_callgraph(value);
  // @@protoc_insertion_point(field_set:hotmethod.RecordArgv.callgraph)
}
inline std::string* RecordArgv::mutable_callgraph() {
  // @@protoc_insertion_point(field_mutable:hotmethod.RecordArgv.callgraph)
  return _internal_mutable_callgraph();
}
inline const std::string& RecordArgv::_internal_callgraph() const {
  return callgraph_.Get();
}
inline void RecordArgv::_internal_set_callgraph(const std::string& value) {
  
  callgraph_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void RecordArgv::set_callgraph(std::string&& value) {
  
  callgraph_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hotmethod.RecordArgv.callgraph)
}
inline void RecordArgv::set_callgraph(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  callgraph_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hotmethod.RecordArgv.callgraph)
}
inline void RecordArgv::set_callgraph(const char* value,
    size_t size) {
  
  callgraph_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hotmethod.RecordArgv.callgraph)
}
inline std::string* RecordArgv::_internal_mutable_callgraph() {
  
  return callgraph_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* RecordArgv::release_callgraph() {
  // @@protoc_insertion_point(field_release:hotmethod.RecordArgv.callgraph)
  return callgraph_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void RecordArgv::set_allocated_callgraph(std::string* callgraph) {
  if (callgraph != nullptr) {
    
  } else {
    
  }
  callgraph_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), callgraph,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hotmethod.RecordArgv.callgraph)
}
inline std::string* RecordArgv::unsafe_arena_release_callgraph() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hotmethod.RecordArgv.callgraph)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return callgraph_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void RecordArgv::unsafe_arena_set_allocated_callgraph(
    std::string* callgraph) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (callgraph != nullptr) {
    
  } else {
    
  }
  callgraph_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      callgraph, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.RecordArgv.callgraph)
}

// -------------------------------------------------------------------

// TaskResult

// string task_id = 1;
inline void TaskResult::clear_task_id() {
  task_id_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TaskResult::task_id() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskResult.task_id)
  return _internal_task_id();
}
inline void TaskResult::set_task_id(const std::string& value) {
  _internal_set_task_id(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskResult.task_id)
}
inline std::string* TaskResult::mutable_task_id() {
  // @@protoc_insertion_point(field_mutable:hotmethod.TaskResult.task_id)
  return _internal_mutable_task_id();
}
inline const std::string& TaskResult::_internal_task_id() const {
  return task_id_.Get();
}
inline void TaskResult::_internal_set_task_id(const std::string& value) {
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TaskResult::set_task_id(std::string&& value) {
  
  task_id_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hotmethod.TaskResult.task_id)
}
inline void TaskResult::set_task_id(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hotmethod.TaskResult.task_id)
}
inline void TaskResult::set_task_id(const char* value,
    size_t size) {
  
  task_id_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hotmethod.TaskResult.task_id)
}
inline std::string* TaskResult::_internal_mutable_task_id() {
  
  return task_id_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TaskResult::release_task_id() {
  // @@protoc_insertion_point(field_release:hotmethod.TaskResult.task_id)
  return task_id_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TaskResult::set_allocated_task_id(std::string* task_id) {
  if (task_id != nullptr) {
    
  } else {
    
  }
  task_id_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), task_id,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hotmethod.TaskResult.task_id)
}
inline std::string* TaskResult::unsafe_arena_release_task_id() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hotmethod.TaskResult.task_id)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return task_id_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TaskResult::unsafe_arena_set_allocated_task_id(
    std::string* task_id) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (task_id != nullptr) {
    
  } else {
    
  }
  task_id_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      task_id, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.TaskResult.task_id)
}

// string error_message = 2;
inline void TaskResult::clear_error_message() {
  error_message_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TaskResult::error_message() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskResult.error_message)
  return _internal_error_message();
}
inline void TaskResult::set_error_message(const std::string& value) {
  _internal_set_error_message(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskResult.error_message)
}
inline std::string* TaskResult::mutable_error_message() {
  // @@protoc_insertion_point(field_mutable:hotmethod.TaskResult.error_message)
  return _internal_mutable_error_message();
}
inline const std::string& TaskResult::_internal_error_message() const {
  return error_message_.Get();
}
inline void TaskResult::_internal_set_error_message(const std::string& value) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TaskResult::set_error_message(std::string&& value) {
  
  error_message_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hotmethod.TaskResult.error_message)
}
inline void TaskResult::set_error_message(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hotmethod.TaskResult.error_message)
}
inline void TaskResult::set_error_message(const char* value,
    size_t size) {
  
  error_message_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hotmethod.TaskResult.error_message)
}
inline std::string* TaskResult::_internal_mutable_error_message() {
  
  return error_message_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TaskResult::release_error_message() {
  // @@protoc_insertion_point(field_release:hotmethod.TaskResult.error_message)
  return error_message_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TaskResult::set_allocated_error_message(std::string* error_message) {
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), error_message,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hotmethod.TaskResult.error_message)
}
inline std::string* TaskResult::unsafe_arena_release_error_message() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hotmethod.TaskResult.error_message)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return error_message_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TaskResult::unsafe_arena_set_allocated_error_message(
    std::string* error_message) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (error_message != nullptr) {
    
  } else {
    
  }
  error_message_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      error_message, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.TaskResult.error_message)
}

// string cos_key = 4;
inline void TaskResult::clear_cos_key() {
  cos_key_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& TaskResult::cos_key() const {
  // @@protoc_insertion_point(field_get:hotmethod.TaskResult.cos_key)
  return _internal_cos_key();
}
inline void TaskResult::set_cos_key(const std::string& value) {
  _internal_set_cos_key(value);
  // @@protoc_insertion_point(field_set:hotmethod.TaskResult.cos_key)
}
inline std::string* TaskResult::mutable_cos_key() {
  // @@protoc_insertion_point(field_mutable:hotmethod.TaskResult.cos_key)
  return _internal_mutable_cos_key();
}
inline const std::string& TaskResult::_internal_cos_key() const {
  return cos_key_.Get();
}
inline void TaskResult::_internal_set_cos_key(const std::string& value) {
  
  cos_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void TaskResult::set_cos_key(std::string&& value) {
  
  cos_key_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:hotmethod.TaskResult.cos_key)
}
inline void TaskResult::set_cos_key(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  cos_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:hotmethod.TaskResult.cos_key)
}
inline void TaskResult::set_cos_key(const char* value,
    size_t size) {
  
  cos_key_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:hotmethod.TaskResult.cos_key)
}
inline std::string* TaskResult::_internal_mutable_cos_key() {
  
  return cos_key_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* TaskResult::release_cos_key() {
  // @@protoc_insertion_point(field_release:hotmethod.TaskResult.cos_key)
  return cos_key_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void TaskResult::set_allocated_cos_key(std::string* cos_key) {
  if (cos_key != nullptr) {
    
  } else {
    
  }
  cos_key_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), cos_key,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:hotmethod.TaskResult.cos_key)
}
inline std::string* TaskResult::unsafe_arena_release_cos_key() {
  // @@protoc_insertion_point(field_unsafe_arena_release:hotmethod.TaskResult.cos_key)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return cos_key_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void TaskResult::unsafe_arena_set_allocated_cos_key(
    std::string* cos_key) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (cos_key != nullptr) {
    
  } else {
    
  }
  cos_key_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      cos_key, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:hotmethod.TaskResult.cos_key)
}

// -------------------------------------------------------------------

// Empty

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace hotmethod

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_hotmethod_2eproto
