// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: hotmethod.proto
#ifndef GRPC_hotmethod_2eproto__INCLUDED
#define GRPC_hotmethod_2eproto__INCLUDED

#include "hotmethod.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace hotmethod {

class Hotmethod final {
 public:
  static constexpr char const* service_full_name() {
    return "hotmethod.Hotmethod";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::hotmethod::Empty* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hotmethod::Empty>> AsyncNotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hotmethod::Empty>>(AsyncNotifyResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hotmethod::Empty>> PrepareAsyncNotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::hotmethod::Empty>>(PrepareAsyncNotifyResultRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hotmethod::Empty>* AsyncNotifyResultRaw(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::hotmethod::Empty>* PrepareAsyncNotifyResultRaw(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::hotmethod::Empty* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>> AsyncNotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>>(AsyncNotifyResultRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>> PrepareAsyncNotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>>(PrepareAsyncNotifyResultRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, std::function<void(::grpc::Status)>) override;
      void NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void NotifyResult(::grpc::ClientContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void NotifyResult(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::hotmethod::Empty* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>* AsyncNotifyResultRaw(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::hotmethod::Empty>* PrepareAsyncNotifyResultRaw(::grpc::ClientContext* context, const ::hotmethod::TaskResult& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_NotifyResult_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status NotifyResult(::grpc::ServerContext* context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_NotifyResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NotifyResult() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_NotifyResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyResult(::grpc::ServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyResult(::grpc::ServerContext* context, ::hotmethod::TaskResult* request, ::grpc::ServerAsyncResponseWriter< ::hotmethod::Empty>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_NotifyResult<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_NotifyResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_NotifyResult() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::hotmethod::TaskResult, ::hotmethod::Empty>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::hotmethod::TaskResult* request, ::hotmethod::Empty* response) { return this->NotifyResult(context, request, response); }));}
    void SetMessageAllocatorFor_NotifyResult(
        ::grpc::experimental::MessageAllocator< ::hotmethod::TaskResult, ::hotmethod::Empty>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc_impl::internal::CallbackUnaryHandler< ::hotmethod::TaskResult, ::hotmethod::Empty>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_NotifyResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyResult(::grpc::ServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NotifyResult(
      ::grpc::CallbackServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NotifyResult(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_NotifyResult<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_NotifyResult<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_NotifyResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NotifyResult() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_NotifyResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyResult(::grpc::ServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_NotifyResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NotifyResult() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_NotifyResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyResult(::grpc::ServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyResult(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_NotifyResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_NotifyResult() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc_impl::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NotifyResult(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_NotifyResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyResult(::grpc::ServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* NotifyResult(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* NotifyResult(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NotifyResult : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NotifyResult() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::hotmethod::TaskResult, ::hotmethod::Empty>(
            [this](::grpc_impl::ServerContext* context,
                   ::grpc_impl::ServerUnaryStreamer<
                     ::hotmethod::TaskResult, ::hotmethod::Empty>* streamer) {
                       return this->StreamedNotifyResult(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NotifyResult() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NotifyResult(::grpc::ServerContext* /*context*/, const ::hotmethod::TaskResult* /*request*/, ::hotmethod::Empty* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNotifyResult(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::hotmethod::TaskResult,::hotmethod::Empty>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_NotifyResult<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_NotifyResult<Service > StreamedService;
};

}  // namespace hotmethod


#endif  // GRPC_hotmethod_2eproto__INCLUDED
