// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: healthcheck.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":     0,
		"SERVING":     1,
		"NOT_SERVING": 2,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_healthcheck_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_healthcheck_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_healthcheck_proto_rawDescGZIP(), []int{1, 0}
}

type HealthCheckRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	HostName       string                 `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	IpAddr         string                 `protobuf:"bytes,2,opt,name=ip_addr,json=ipAddr,proto3" json:"ip_addr,omitempty"`
	Uid            string                 `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	AgentVersion   string                 `protobuf:"bytes,4,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	SelfPstats     *PidStats              `protobuf:"bytes,5,opt,name=self_pstats,json=selfPstats,proto3" json:"self_pstats,omitempty"`
	ChildrenPstats *PidStats              `protobuf:"bytes,6,opt,name=children_pstats,json=childrenPstats,proto3" json:"children_pstats,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_healthcheck_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_healthcheck_proto_rawDescGZIP(), []int{0}
}

func (x *HealthCheckRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *HealthCheckRequest) GetIpAddr() string {
	if x != nil {
		return x.IpAddr
	}
	return ""
}

func (x *HealthCheckRequest) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *HealthCheckRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *HealthCheckRequest) GetSelfPstats() *PidStats {
	if x != nil {
		return x.SelfPstats
	}
	return nil
}

func (x *HealthCheckRequest) GetChildrenPstats() *PidStats {
	if x != nil {
		return x.ChildrenPstats
	}
	return nil
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=healthcheck.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	Pending       bool                              `protobuf:"varint,2,opt,name=pending,proto3" json:"pending,omitempty"`
	TaskDesc      *TaskDesc                         `protobuf:"bytes,3,opt,name=task_desc,json=taskDesc,proto3" json:"task_desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_healthcheck_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_healthcheck_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_healthcheck_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

func (x *HealthCheckResponse) GetPending() bool {
	if x != nil {
		return x.Pending
	}
	return false
}

func (x *HealthCheckResponse) GetTaskDesc() *TaskDesc {
	if x != nil {
		return x.TaskDesc
	}
	return nil
}

var File_healthcheck_proto protoreflect.FileDescriptor

const file_healthcheck_proto_rawDesc = "" +
	"\n" +
	"\x11healthcheck.proto\x12\vhealthcheck\x1a\fcommon.proto\x1a\x0fhotmethod.proto\"\xef\x01\n" +
	"\x12HealthCheckRequest\x12\x1b\n" +
	"\thost_name\x18\x01 \x01(\tR\bhostName\x12\x17\n" +
	"\aip_addr\x18\x02 \x01(\tR\x06ipAddr\x12\x10\n" +
	"\x03uid\x18\x03 \x01(\tR\x03uid\x12#\n" +
	"\ragent_version\x18\x04 \x01(\tR\fagentVersion\x121\n" +
	"\vself_pstats\x18\x05 \x01(\v2\x10.common.PidStatsR\n" +
	"selfPstats\x129\n" +
	"\x0fchildren_pstats\x18\x06 \x01(\v2\x10.common.PidStatsR\x0echildrenPstats\"\xe5\x01\n" +
	"\x13HealthCheckResponse\x12F\n" +
	"\x06status\x18\x01 \x01(\x0e2..healthcheck.HealthCheckResponse.ServingStatusR\x06status\x12\x18\n" +
	"\apending\x18\x02 \x01(\bR\apending\x120\n" +
	"\ttask_desc\x18\x03 \x01(\v2\x13.hotmethod.TaskDescR\btaskDesc\":\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x022V\n" +
	"\vHealthCheck\x12G\n" +
	"\x02Do\x12\x1f.healthcheck.HealthCheckRequest\x1a .healthcheck.HealthCheckResponseB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_healthcheck_proto_rawDescOnce sync.Once
	file_healthcheck_proto_rawDescData []byte
)

func file_healthcheck_proto_rawDescGZIP() []byte {
	file_healthcheck_proto_rawDescOnce.Do(func() {
		file_healthcheck_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_healthcheck_proto_rawDesc), len(file_healthcheck_proto_rawDesc)))
	})
	return file_healthcheck_proto_rawDescData
}

var file_healthcheck_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_healthcheck_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_healthcheck_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0), // 0: healthcheck.HealthCheckResponse.ServingStatus
	(*HealthCheckRequest)(nil),             // 1: healthcheck.HealthCheckRequest
	(*HealthCheckResponse)(nil),            // 2: healthcheck.HealthCheckResponse
	(*PidStats)(nil),                       // 3: common.PidStats
	(*TaskDesc)(nil),                       // 4: hotmethod.TaskDesc
}
var file_healthcheck_proto_depIdxs = []int32{
	3, // 0: healthcheck.HealthCheckRequest.self_pstats:type_name -> common.PidStats
	3, // 1: healthcheck.HealthCheckRequest.children_pstats:type_name -> common.PidStats
	0, // 2: healthcheck.HealthCheckResponse.status:type_name -> healthcheck.HealthCheckResponse.ServingStatus
	4, // 3: healthcheck.HealthCheckResponse.task_desc:type_name -> hotmethod.TaskDesc
	1, // 4: healthcheck.HealthCheck.Do:input_type -> healthcheck.HealthCheckRequest
	2, // 5: healthcheck.HealthCheck.Do:output_type -> healthcheck.HealthCheckResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_healthcheck_proto_init() }
func file_healthcheck_proto_init() {
	if File_healthcheck_proto != nil {
		return
	}
	file_common_proto_init()
	file_hotmethod_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_healthcheck_proto_rawDesc), len(file_healthcheck_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_healthcheck_proto_goTypes,
		DependencyIndexes: file_healthcheck_proto_depIdxs,
		EnumInfos:         file_healthcheck_proto_enumTypes,
		MessageInfos:      file_healthcheck_proto_msgTypes,
	}.Build()
	File_healthcheck_proto = out.File
	file_healthcheck_proto_goTypes = nil
	file_healthcheck_proto_depIdxs = nil
}
