// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: hotmethod.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TaskDesc struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	TaskId   string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType uint32                 `protobuf:"varint,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	// profiler_type: 0=perf, 1=eBPF, 2=py-spy
	ProfilerType  uint32      `protobuf:"varint,3,opt,name=profiler_type,json=profilerType,proto3" json:"profiler_type,omitempty"`
	SampleArgv    *RecordArgv `protobuf:"bytes,4,opt,name=sample_argv,json=sampleArgv,proto3" json:"sample_argv,omitempty"`
	ContainerName string      `protobuf:"bytes,5,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	TimeoutSec    uint32      `protobuf:"varint,7,opt,name=timeout_sec,json=timeoutSec,proto3" json:"timeout_sec,omitempty"`
	CosConfig     *CosConfig  `protobuf:"bytes,8,opt,name=cos_config,json=cosConfig,proto3" json:"cos_config,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskDesc) Reset() {
	*x = TaskDesc{}
	mi := &file_hotmethod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskDesc) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskDesc) ProtoMessage() {}

func (x *TaskDesc) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskDesc.ProtoReflect.Descriptor instead.
func (*TaskDesc) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{0}
}

func (x *TaskDesc) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskDesc) GetTaskType() uint32 {
	if x != nil {
		return x.TaskType
	}
	return 0
}

func (x *TaskDesc) GetProfilerType() uint32 {
	if x != nil {
		return x.ProfilerType
	}
	return 0
}

func (x *TaskDesc) GetSampleArgv() *RecordArgv {
	if x != nil {
		return x.SampleArgv
	}
	return nil
}

func (x *TaskDesc) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *TaskDesc) GetTimeoutSec() uint32 {
	if x != nil {
		return x.TimeoutSec
	}
	return 0
}

func (x *TaskDesc) GetCosConfig() *CosConfig {
	if x != nil {
		return x.CosConfig
	}
	return nil
}

type RecordArgv struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hz            uint32                 `protobuf:"varint,1,opt,name=hz,proto3" json:"hz,omitempty"`
	Duration      uint64                 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Pid           int32                  `protobuf:"varint,3,opt,name=pid,proto3" json:"pid,omitempty"`
	Callgraph     string                 `protobuf:"bytes,4,opt,name=callgraph,proto3" json:"callgraph,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordArgv) Reset() {
	*x = RecordArgv{}
	mi := &file_hotmethod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordArgv) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordArgv) ProtoMessage() {}

func (x *RecordArgv) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordArgv.ProtoReflect.Descriptor instead.
func (*RecordArgv) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{1}
}

func (x *RecordArgv) GetHz() uint32 {
	if x != nil {
		return x.Hz
	}
	return 0
}

func (x *RecordArgv) GetDuration() uint64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *RecordArgv) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *RecordArgv) GetCallgraph() string {
	if x != nil {
		return x.Callgraph
	}
	return ""
}

type TaskResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CosKey        string                 `protobuf:"bytes,4,opt,name=cos_key,json=cosKey,proto3" json:"cos_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_hotmethod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{2}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *TaskResult) GetCosKey() string {
	if x != nil {
		return x.CosKey
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_hotmethod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_hotmethod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_hotmethod_proto_rawDescGZIP(), []int{3}
}

var File_hotmethod_proto protoreflect.FileDescriptor

const file_hotmethod_proto_rawDesc = "" +
	"\n" +
	"\x0fhotmethod.proto\x12\thotmethod\x1a\fcommon.proto\"\x97\x02\n" +
	"\bTaskDesc\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\rR\btaskType\x12#\n" +
	"\rprofiler_type\x18\x03 \x01(\rR\fprofilerType\x126\n" +
	"\vsample_argv\x18\x04 \x01(\v2\x15.hotmethod.RecordArgvR\n" +
	"sampleArgv\x12%\n" +
	"\x0econtainer_name\x18\x05 \x01(\tR\rcontainerName\x12\x1f\n" +
	"\vtimeout_sec\x18\a \x01(\rR\n" +
	"timeoutSec\x120\n" +
	"\n" +
	"cos_config\x18\b \x01(\v2\x11.common.CosConfigR\tcosConfig\"h\n" +
	"\n" +
	"RecordArgv\x12\x0e\n" +
	"\x02hz\x18\x01 \x01(\rR\x02hz\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\x04R\bduration\x12\x10\n" +
	"\x03pid\x18\x03 \x01(\x05R\x03pid\x12\x1c\n" +
	"\tcallgraph\x18\x04 \x01(\tR\tcallgraph\"c\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x17\n" +
	"\acos_key\x18\x04 \x01(\tR\x06cosKey\"\a\n" +
	"\x05Empty2D\n" +
	"\tHotmethod\x127\n" +
	"\fNotifyResult\x12\x15.hotmethod.TaskResult\x1a\x10.hotmethod.EmptyB\n" +
	"Z\b./;protob\x06proto3"

var (
	file_hotmethod_proto_rawDescOnce sync.Once
	file_hotmethod_proto_rawDescData []byte
)

func file_hotmethod_proto_rawDescGZIP() []byte {
	file_hotmethod_proto_rawDescOnce.Do(func() {
		file_hotmethod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotmethod_proto_rawDesc), len(file_hotmethod_proto_rawDesc)))
	})
	return file_hotmethod_proto_rawDescData
}

var file_hotmethod_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_hotmethod_proto_goTypes = []any{
	(*TaskDesc)(nil),   // 0: hotmethod.TaskDesc
	(*RecordArgv)(nil), // 1: hotmethod.RecordArgv
	(*TaskResult)(nil), // 2: hotmethod.TaskResult
	(*Empty)(nil),      // 3: hotmethod.Empty
	(*CosConfig)(nil),  // 4: common.CosConfig
}
var file_hotmethod_proto_depIdxs = []int32{
	1, // 0: hotmethod.TaskDesc.sample_argv:type_name -> hotmethod.RecordArgv
	4, // 1: hotmethod.TaskDesc.cos_config:type_name -> common.CosConfig
	2, // 2: hotmethod.Hotmethod.NotifyResult:input_type -> hotmethod.TaskResult
	3, // 3: hotmethod.Hotmethod.NotifyResult:output_type -> hotmethod.Empty
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_hotmethod_proto_init() }
func file_hotmethod_proto_init() {
	if File_hotmethod_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotmethod_proto_rawDesc), len(file_hotmethod_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hotmethod_proto_goTypes,
		DependencyIndexes: file_hotmethod_proto_depIdxs,
		MessageInfos:      file_hotmethod_proto_msgTypes,
	}.Build()
	File_hotmethod_proto = out.File
	file_hotmethod_proto_goTypes = nil
	file_hotmethod_proto_depIdxs = nil
}
